### ISSUE TITLE
No Images in Firefox Addon

### ISSUE THREAD

**Issue by M1NDWARE** [ge-ku/Ban-Checker-for-Steam#10]
Hi,
this problem is only present in the firefox version. The ban information is correct but the avatars are broken.

![bugff](https://user-images.githubusercontent.com/32162636/38466123-a156f6f4-3b24-11e8-9a3e-c81c31b9ecdc.PNG)

**Comment by ge-ku** [comment]
Thanks for letting me know, looks like steamcommunity.com switched to https but these images are only available via http and it causes this issue, I'll try to fix it soon.

**Comment by ge-ku** [comment]
[Fixed now](https://github.com/ge-ku/Ban-Checker-for-Steam/commit/5a4e25b59adf43873a220b6fdbac2b82bcf6c25e). I uploaded new version to Chrome Store (it wasn't only FF) and AMO, should be up soon, version number is 1.0.11.
