### ISSUE TITLE
Needs updating to support the new GDPR steam data

### ISSUE THREAD

**Issue by taraldr** [ge-ku/Ban-Checker-for-Steam#11]
You can now view your entire CSGO history in steam, every single match, and who played it.
This plugin should be updated to support this data.

see
https://www.reddit.com/r/GlobalOffensive/comments/8lyzb6/so_the_steam_client_has_been_keeping_track_of/

**Comment by ge-ku** [comment]
Wow, that's neat! I'll take a deeper look on a weekend, thanks for notifying me.

**Comment by ge-ku** [comment]
Added some initial support, there's a button to load your whole match history and another button to check loaded matches for bans.
