### ISSUE TITLE
Show bans in player reports tab

### ISSUE THREAD

**Issue by wischi-chr** [ge-ku/Ban-Checker-for-Steam#12]
Would be nice if the plugin could show similar information on the [reports tab](https://steamcommunity.com/my/gcpd/730/?tab=playerreports)

_Possible duplicate: #15_

**Comment by ge-ku** [comment]
This is on my todo list, I'll try to implement it next weekend.

**Comment by ge-ku** [comment]
This should work now (starting with version 1.1.8).
