### ISSUE TITLE
not an issue a suggestion (dont knowhow to use github

### ISSUE THREAD

**Issue by SivalalR** [ge-ku/Ban-Checker-for-Steam#15]
if  u could show the bans along side the reports it would be cool

**Comment by ge-ku** [comment]
I'm planning to add similar functionality to reports tab on the next weekend.

**Comment by SivalalR** [comment]
Thank you for the extension

**Comment by ge-ku** [comment]
This should work now starting with v1.1.8

**Comment by SivalalR** [comment]
Cudos
