### ISSUE TITLE
proposal for renewal

### ISSUE THREAD

**Issue by panikajo** [ge-ku/Ban-Checker-for-Steam#24]
u can use this javascript for you're extension.
https://github.com/WillsonHaw/VacBanChecker 
I think that js beauty you're extension.
https://raw.githubusercontent.com/WillsonHaw/VacBanChecker/master/docs/instructions.gif

**Comment by ge-ku** [comment]
I'm not sure what you mean by that, do you mean how it looks visually?

**Comment by panikajo** [comment]
You can add this to your extension.
I showed how it will look.

**Comment by ge-ku** [comment]
Updated extension with new visuals (they are not the same as linked above but similar) and it's for Friends page only, group members were not changed.
