### ISSUE TITLE
Checking if player is banned even if he has a private profile

### ISSUE THREAD

**Issue by vdiehl** [ge-ku/Ban-Checker-for-Steam#26]
As far as i know, this extension can't identify if a player has a vac or ow ban if his profile is set as private. These days i was using rbot (ReportBot.io) to report a player that have a private profile and the rbot show me that he was already ow banned. Maybe this feature can be implemented in this extension.

**Comment by ge-ku** [comment]
I'm pretty sure it works with private profiles, can you give me an example profile so I can check it?

**Comment by vdiehl** [comment]
Sure!!

https://steamcommunity.com/id/rolimfisio93

**Comment by ge-ku** [comment]
This guy is not banned according to Steam API, I'm not sure where ReportBot.io gets its data and if it's accurate.

You can check it yourself (replace API_KEY with your Steam API key):
http://api.steampowered.com/ISteamUser/GetPlayerBans/v1/?key=API_KEY&steamids=76561198847341924

Here are some examples where it does work.
Private profile - https://steamcommunity.com/profiles/76561198129612890/
Not yet setup profile - https://steamcommunity.com/profiles/76561197985751231

Replace API_KEY with your Steam API key again:
http://api.steampowered.com/ISteamUser/GetPlayerBans/v1/?key=API_KEY&steamids=76561198129612890,76561197985751231

**Comment by ge-ku** [comment]
He's also not banned according to SteamDB and some other third-party websites I checked.

There's also [this statement from Valve about report bots](https://np.reddit.com/r/GlobalOffensive/comments/89qk3l/i_emailed_a_valve_employee_about_csgo_and_got_a/dwtqe94/). I'll close this issue for now as I don't know how to resolve it (and if it's even possible) but let me know if you have new information, I'm curious.
