### ISSUE TITLE
matchhistorycompetitive doesn't show vac ban status

### ISSUE THREAD

**Issue by RalphORama** [ge-ku/Ban-Checker-for-Steam#28]
## Installation Details

Chrome: `Version 71.0.3551.3 (Official Build) dev (64-bit)`
Plugin: `1.2.2.1` (Installed from chrome web store)
Settings:

- Custom API key set (double-checked)
- `Do not write green text ("No Bans for this player.")` set to `false`

## My issue

The plugin functions properly on pages like `my/friends/coplay/` and `my/friends/`, however no action is observed on `my/gcpd/730?tab=matchhistorycompetitive`.  On the first two pages, I can observe requests to the API in the network log: `https://api.steampowered.com/ISteamUser/GetPlayerBans/v1/?key=<custom API key>&steamids=<lots of steamIDs>`.  However, on the latter page, no such API requests are present in the network log.  There are only one or two errors present in the console, and neither are related to the Ban Checker plugin.

**However,** the "fun stats for loaded matches" box in the bottom left corner is still loaded.

## Screenshots

**Network log comparison**
![network log screenshot](https://vgy.me/ZACZyU.png)

**matchhistorycompetitive page**
![matchhistorycompetitive page](https://vgy.me/bH3pOT.png)

**Comment by ge-ku** [comment]
Just to make sure, did you click on "Check loaded matches for bans" button? It's not automatically started on these pages.

**Comment by RalphORama** [comment]
@ge-ku I'm blind, didn't even see that

Thanks very much
