### ISSUE TITLE
Check loaded matches for bans

### ISSUE THREAD

**Issue by roennow** [ge-ku/Ban-Checker-for-Steam#30]
This doesn't work for me anymore

> Error while scanning players for bans:
> TypeError: Failed to fetch
> 
> Couldn't scan for bans after 3 retries :(

Here is what is says in the dev console

> Access to fetch at 'https://api.steampowered.com/ISteamUser/GetPlayerBans/v1/?key=myredactedapikey&steamids=76561197960390649,76561197982247467,76561198016732735,76561198024747249,76561198075265998,76561198030225254,76561197970347254,76561198312192951,76561198815481267,76561198420948511,76561197960489058,76561198037901278,76561197970363054,76561198177899414,76561198081882958,76561198055739722,76561198053333977,76561198133940131,76561197980438956,76561198138645030,76561198268191236,76561198090044786,76561198180001247,76561198147530455,76561198038415771,76561198078623137,76561198149323663,76561198007914067,76561197981993943,76561197966811283,76561197960675929,76561198008111266,76561198370567430,76561197964661103,76561198367781551,76561198355338117,76561198393450287,76561198123573162,76561198400756077,76561198049686114,76561198069247451,76561198145741427,76561198196680791,76561198145124674,76561198232181452,76561198366759721,76561197976279480,76561198143271917,76561198205646512,76561198071063871,76561198175395013,76561198274701099,76561198177720273,76561198399409076,76561198414391867' from origin 'chrome-extension://canbadmphamemnmdfngmcabnjmjgaiki' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

**Comment by ge-ku** [comment]
Couldn't reproduce, still works on my end. What's your browser version? As far as I remember CORS shouldn't affect extension as long as it has correct permission granted.

**Comment by roennow** [comment]
Chrome 72.0.3626.81 64 bit on windows 10

Use Ublock Origin and Ghostery but both are turned off/trusted and if I open the url the json shows up fine

**Comment by ge-ku** [comment]
Same Chrome version here and works for me.
Try going to extension settings (chrome://extensions/?id=canbadmphamemnmdfngmcabnjmjgaiki or right click on icon and click "Manage extensions") and check if permissions are granted. Same error appears if I remove https://api.steampowered.com/* access.
![image](https://user-images.githubusercontent.com/11873225/52169445-45dd4f80-2741-11e9-9b33-d5b9b58bfb56.png)

**Comment by roennow** [comment]
Okay that was disabled for some reason. Have had it working and the rule was there. Don't know how that could happen. Thanks!
