### ISSUE TITLE
"Load whole match history" stops after 783 games

### ISSUE THREAD

**Issue by Squamoto** [ge-ku/Ban-Checker-for-Steam#31]
The script that is supposed to load all MM games at [this page](https://steamcommunity.com/my/gcpd/730?tab=matchhistorycompetitive) stops after 783 games, every time. The reason might be on Valve's end tho, as there is no continuation token returned to load the next page. I have set my own API key.

**Comment by Squamoto** [comment]
It is an issue on Steam's side:

"Thanks for reaching out about this.

Earlier this year we expired all Competitive match histories and corresponding meta-data prior to November 2017 to reclaim CS:GO storage space used for various things. Unfortunately, because of this you will not be able to see Competitive matches on your Account Data page prior to November 2017. This data has been permanently deleted and cannot be recovered. We apologize for the inconvenience.

If there's something else we can help with please let us know. 

Regards,	
Hal"

**Comment by ge-ku** [comment]
Thanks for letting me know, this is unfortunate, I liked being able to look at my history of matches. :(

**Comment by FalkF** [comment]
YOU MONSTERS!!
