### ISSUE TITLE
Release on Microsoft Edge Addons catalog

### ISSUE THREAD

**Issue by cherinyy** [ge-ku/Ban-Checker-for-Steam#35]
Hello Geku,

I want to know if you are willing to publish the plugin in Microsoft Edge Addons catalog.

This request is because users in Mainland China cannot directly access the Chrome Web Store.

But Microsoft Edge Addons catalog can.

So I opened this issue.

Thanks

**Comment by ge-ku** [comment]
Hello, it looks like with new Edge (Chromium version) I can simply upload Chrome version with no changes, should be easy. I'll try to do it a bit later.

**Comment by ge-ku** [comment]
Sorry for delay, there is still no Edge for Linux so I can't test it right now. I sent it anyway without testing, hopefully it'll work :) It's being reviewed right now, I'll post a link once it's published.

**Comment by cherinyy** [comment]
Ok, thank you!
I will help test by then :)

**Comment by ge-ku** [comment]
Review passed, here it is https://microsoftedge.microsoft.com/addons/detail/ban-checker-for-steam/jpfpinbbmcpbnnohhdhpibfpfoikgjjf
Let me know if it does or doesn't work at all :)

**Comment by cherinyy** [comment]
> Review passed, here it is https://microsoftedge.microsoft.com/addons/detail/ban-checker-for-steam/jpfpinbbmcpbnnohhdhpibfpfoikgjjf
> Let me know if it does or doesn't work at all :)

Thank you again! I haven't found any problems at the moment, I will let you know if there are any.
