### ISSUE TITLE
Firefox addon planned?

### ISSUE THREAD

**Issue by Trollwut** [ge-ku/Ban-Checker-for-Steam#7]
Is there a Firefox version of this addon planned? :-)

**Comment by ge-ku** [comment]
Sorry for a late reply. Possibly, with [WebExtension](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Porting_a_Google_Chrome_extension) standard it should "just work" as is, I'll try to test it soon.

**Comment by Trollwut** [comment]
Yeah baby, thanks for info!

**Comment by ge-ku** [comment]
Here it is: https://addons.mozilla.org/firefox/addon/ban-checker/
It's currently being reviewed by AMO and if everything's fine will be available soon.

**Comment by guihkx** [comment]
I just found this thread on Google. Thanks for the Firefox port!

**Comment by ge-ku** [comment]
[Now approved!](https://addons.mozilla.org/firefox/addon/ban-checker/) I hope it works, feel free to create new issues if you notice problems.
